#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SalesSystem")]
	public partial class DBSalesContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public DBSalesContextDataContext() : 
				base(global::linqToSql.Properties.Settings.Default.SalesSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBSalesContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSalesContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSalesContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSalesContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AllCustomers")]
		public ISingleResult<AllCustomersResult> AllCustomers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<AllCustomersResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pro_ID;
		
		private string _Pro_Name;
		
		private System.Nullable<float> _Qty;
		
		private System.Nullable<float> _Gomla_Price;
		
		private System.Nullable<float> _Sale_Price;
		
		private string _Barcode;
		
		private System.Nullable<float> _MinQty;
		
		private System.Nullable<float> _MaxDiscount;
		
		private System.Nullable<int> _Group_ID;
		
		private string _Main_UnitName;
		
		private System.Nullable<int> _Main_UnitID;
		
		private string _Sale_UnitName;
		
		private System.Nullable<int> _Sale_UnitID;
		
		private string _Buy_UnitName;
		
		private System.Nullable<int> _Buy_UnitID;
		
		private System.Nullable<float> _GomlaGomla_Price;
		
		private System.Nullable<float> _Sale_PriceAfterTax;
		
		private System.Nullable<float> _Gomla_PriceAfterTax;
		
		private System.Nullable<float> _GomlaGomla_PriceAfterTax;
		
		private System.Nullable<float> _TaxValue;
		
		private string _ISunderTaxValue;
		
		private string _Pro_Type;
		
		private string _HaveExpireDate;
		
		private System.Nullable<float> _CoponValue;
		
		private string _Company_Name;
		
		private string _Effective_Name;
		
		private string _BackColor;
		
		private string _NewPath;
		
		private string _Printer_Name;
		
		private System.Nullable<int> _NumDayGym;
		
		private string _HaveRicaby;
		
		private string _HaveStore;
		
		private string _PrintINBasicBranch;
		
		private string _HaveSize;
		
		private System.Nullable<float> _Buy_Price;
		
		private System.Nullable<int> _HeadPro_ID;
		
		private string _Size;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPro_IDChanging(int value);
    partial void OnPro_IDChanged();
    partial void OnPro_NameChanging(string value);
    partial void OnPro_NameChanged();
    partial void OnQtyChanging(System.Nullable<float> value);
    partial void OnQtyChanged();
    partial void OnGomla_PriceChanging(System.Nullable<float> value);
    partial void OnGomla_PriceChanged();
    partial void OnSale_PriceChanging(System.Nullable<float> value);
    partial void OnSale_PriceChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnMinQtyChanging(System.Nullable<float> value);
    partial void OnMinQtyChanged();
    partial void OnMaxDiscountChanging(System.Nullable<float> value);
    partial void OnMaxDiscountChanged();
    partial void OnGroup_IDChanging(System.Nullable<int> value);
    partial void OnGroup_IDChanged();
    partial void OnMain_UnitNameChanging(string value);
    partial void OnMain_UnitNameChanged();
    partial void OnMain_UnitIDChanging(System.Nullable<int> value);
    partial void OnMain_UnitIDChanged();
    partial void OnSale_UnitNameChanging(string value);
    partial void OnSale_UnitNameChanged();
    partial void OnSale_UnitIDChanging(System.Nullable<int> value);
    partial void OnSale_UnitIDChanged();
    partial void OnBuy_UnitNameChanging(string value);
    partial void OnBuy_UnitNameChanged();
    partial void OnBuy_UnitIDChanging(System.Nullable<int> value);
    partial void OnBuy_UnitIDChanged();
    partial void OnGomlaGomla_PriceChanging(System.Nullable<float> value);
    partial void OnGomlaGomla_PriceChanged();
    partial void OnSale_PriceAfterTaxChanging(System.Nullable<float> value);
    partial void OnSale_PriceAfterTaxChanged();
    partial void OnGomla_PriceAfterTaxChanging(System.Nullable<float> value);
    partial void OnGomla_PriceAfterTaxChanged();
    partial void OnGomlaGomla_PriceAfterTaxChanging(System.Nullable<float> value);
    partial void OnGomlaGomla_PriceAfterTaxChanged();
    partial void OnTaxValueChanging(System.Nullable<float> value);
    partial void OnTaxValueChanged();
    partial void OnISunderTaxValueChanging(string value);
    partial void OnISunderTaxValueChanged();
    partial void OnPro_TypeChanging(string value);
    partial void OnPro_TypeChanged();
    partial void OnHaveExpireDateChanging(string value);
    partial void OnHaveExpireDateChanged();
    partial void OnCoponValueChanging(System.Nullable<float> value);
    partial void OnCoponValueChanged();
    partial void OnCompany_NameChanging(string value);
    partial void OnCompany_NameChanged();
    partial void OnEffective_NameChanging(string value);
    partial void OnEffective_NameChanged();
    partial void OnBackColorChanging(string value);
    partial void OnBackColorChanged();
    partial void OnNewPathChanging(string value);
    partial void OnNewPathChanged();
    partial void OnPrinter_NameChanging(string value);
    partial void OnPrinter_NameChanged();
    partial void OnNumDayGymChanging(System.Nullable<int> value);
    partial void OnNumDayGymChanged();
    partial void OnHaveRicabyChanging(string value);
    partial void OnHaveRicabyChanged();
    partial void OnHaveStoreChanging(string value);
    partial void OnHaveStoreChanged();
    partial void OnPrintINBasicBranchChanging(string value);
    partial void OnPrintINBasicBranchChanged();
    partial void OnHaveSizeChanging(string value);
    partial void OnHaveSizeChanged();
    partial void OnBuy_PriceChanging(System.Nullable<float> value);
    partial void OnBuy_PriceChanged();
    partial void OnHeadPro_IDChanging(System.Nullable<int> value);
    partial void OnHeadPro_IDChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pro_ID
		{
			get
			{
				return this._Pro_ID;
			}
			set
			{
				if ((this._Pro_ID != value))
				{
					this.OnPro_IDChanging(value);
					this.SendPropertyChanging();
					this._Pro_ID = value;
					this.SendPropertyChanged("Pro_ID");
					this.OnPro_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="NVarChar(300)")]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this.OnPro_NameChanging(value);
					this.SendPropertyChanging();
					this._Pro_Name = value;
					this.SendPropertyChanged("Pro_Name");
					this.OnPro_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Real")]
		public System.Nullable<float> Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gomla_Price", DbType="Real")]
		public System.Nullable<float> Gomla_Price
		{
			get
			{
				return this._Gomla_Price;
			}
			set
			{
				if ((this._Gomla_Price != value))
				{
					this.OnGomla_PriceChanging(value);
					this.SendPropertyChanging();
					this._Gomla_Price = value;
					this.SendPropertyChanged("Gomla_Price");
					this.OnGomla_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_Price", DbType="Real")]
		public System.Nullable<float> Sale_Price
		{
			get
			{
				return this._Sale_Price;
			}
			set
			{
				if ((this._Sale_Price != value))
				{
					this.OnSale_PriceChanging(value);
					this.SendPropertyChanging();
					this._Sale_Price = value;
					this.SendPropertyChanged("Sale_Price");
					this.OnSale_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(300)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQty", DbType="Real")]
		public System.Nullable<float> MinQty
		{
			get
			{
				return this._MinQty;
			}
			set
			{
				if ((this._MinQty != value))
				{
					this.OnMinQtyChanging(value);
					this.SendPropertyChanging();
					this._MinQty = value;
					this.SendPropertyChanged("MinQty");
					this.OnMinQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDiscount", DbType="Real")]
		public System.Nullable<float> MaxDiscount
		{
			get
			{
				return this._MaxDiscount;
			}
			set
			{
				if ((this._MaxDiscount != value))
				{
					this.OnMaxDiscountChanging(value);
					this.SendPropertyChanging();
					this._MaxDiscount = value;
					this.SendPropertyChanged("MaxDiscount");
					this.OnMaxDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_ID", DbType="Int")]
		public System.Nullable<int> Group_ID
		{
			get
			{
				return this._Group_ID;
			}
			set
			{
				if ((this._Group_ID != value))
				{
					this.OnGroup_IDChanging(value);
					this.SendPropertyChanging();
					this._Group_ID = value;
					this.SendPropertyChanged("Group_ID");
					this.OnGroup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_UnitName", DbType="NVarChar(250)")]
		public string Main_UnitName
		{
			get
			{
				return this._Main_UnitName;
			}
			set
			{
				if ((this._Main_UnitName != value))
				{
					this.OnMain_UnitNameChanging(value);
					this.SendPropertyChanging();
					this._Main_UnitName = value;
					this.SendPropertyChanged("Main_UnitName");
					this.OnMain_UnitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_UnitID", DbType="Int")]
		public System.Nullable<int> Main_UnitID
		{
			get
			{
				return this._Main_UnitID;
			}
			set
			{
				if ((this._Main_UnitID != value))
				{
					this.OnMain_UnitIDChanging(value);
					this.SendPropertyChanging();
					this._Main_UnitID = value;
					this.SendPropertyChanged("Main_UnitID");
					this.OnMain_UnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_UnitName", DbType="NVarChar(250)")]
		public string Sale_UnitName
		{
			get
			{
				return this._Sale_UnitName;
			}
			set
			{
				if ((this._Sale_UnitName != value))
				{
					this.OnSale_UnitNameChanging(value);
					this.SendPropertyChanging();
					this._Sale_UnitName = value;
					this.SendPropertyChanged("Sale_UnitName");
					this.OnSale_UnitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_UnitID", DbType="Int")]
		public System.Nullable<int> Sale_UnitID
		{
			get
			{
				return this._Sale_UnitID;
			}
			set
			{
				if ((this._Sale_UnitID != value))
				{
					this.OnSale_UnitIDChanging(value);
					this.SendPropertyChanging();
					this._Sale_UnitID = value;
					this.SendPropertyChanged("Sale_UnitID");
					this.OnSale_UnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_UnitName", DbType="NVarChar(250)")]
		public string Buy_UnitName
		{
			get
			{
				return this._Buy_UnitName;
			}
			set
			{
				if ((this._Buy_UnitName != value))
				{
					this.OnBuy_UnitNameChanging(value);
					this.SendPropertyChanging();
					this._Buy_UnitName = value;
					this.SendPropertyChanged("Buy_UnitName");
					this.OnBuy_UnitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_UnitID", DbType="Int")]
		public System.Nullable<int> Buy_UnitID
		{
			get
			{
				return this._Buy_UnitID;
			}
			set
			{
				if ((this._Buy_UnitID != value))
				{
					this.OnBuy_UnitIDChanging(value);
					this.SendPropertyChanging();
					this._Buy_UnitID = value;
					this.SendPropertyChanged("Buy_UnitID");
					this.OnBuy_UnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GomlaGomla_Price", DbType="Real")]
		public System.Nullable<float> GomlaGomla_Price
		{
			get
			{
				return this._GomlaGomla_Price;
			}
			set
			{
				if ((this._GomlaGomla_Price != value))
				{
					this.OnGomlaGomla_PriceChanging(value);
					this.SendPropertyChanging();
					this._GomlaGomla_Price = value;
					this.SendPropertyChanged("GomlaGomla_Price");
					this.OnGomlaGomla_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_PriceAfterTax", DbType="Real")]
		public System.Nullable<float> Sale_PriceAfterTax
		{
			get
			{
				return this._Sale_PriceAfterTax;
			}
			set
			{
				if ((this._Sale_PriceAfterTax != value))
				{
					this.OnSale_PriceAfterTaxChanging(value);
					this.SendPropertyChanging();
					this._Sale_PriceAfterTax = value;
					this.SendPropertyChanged("Sale_PriceAfterTax");
					this.OnSale_PriceAfterTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gomla_PriceAfterTax", DbType="Real")]
		public System.Nullable<float> Gomla_PriceAfterTax
		{
			get
			{
				return this._Gomla_PriceAfterTax;
			}
			set
			{
				if ((this._Gomla_PriceAfterTax != value))
				{
					this.OnGomla_PriceAfterTaxChanging(value);
					this.SendPropertyChanging();
					this._Gomla_PriceAfterTax = value;
					this.SendPropertyChanged("Gomla_PriceAfterTax");
					this.OnGomla_PriceAfterTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GomlaGomla_PriceAfterTax", DbType="Real")]
		public System.Nullable<float> GomlaGomla_PriceAfterTax
		{
			get
			{
				return this._GomlaGomla_PriceAfterTax;
			}
			set
			{
				if ((this._GomlaGomla_PriceAfterTax != value))
				{
					this.OnGomlaGomla_PriceAfterTaxChanging(value);
					this.SendPropertyChanging();
					this._GomlaGomla_PriceAfterTax = value;
					this.SendPropertyChanged("GomlaGomla_PriceAfterTax");
					this.OnGomlaGomla_PriceAfterTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Real")]
		public System.Nullable<float> TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this.OnTaxValueChanging(value);
					this.SendPropertyChanging();
					this._TaxValue = value;
					this.SendPropertyChanged("TaxValue");
					this.OnTaxValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISunderTaxValue", DbType="NVarChar(250)")]
		public string ISunderTaxValue
		{
			get
			{
				return this._ISunderTaxValue;
			}
			set
			{
				if ((this._ISunderTaxValue != value))
				{
					this.OnISunderTaxValueChanging(value);
					this.SendPropertyChanging();
					this._ISunderTaxValue = value;
					this.SendPropertyChanged("ISunderTaxValue");
					this.OnISunderTaxValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Type", DbType="NVarChar(50)")]
		public string Pro_Type
		{
			get
			{
				return this._Pro_Type;
			}
			set
			{
				if ((this._Pro_Type != value))
				{
					this.OnPro_TypeChanging(value);
					this.SendPropertyChanging();
					this._Pro_Type = value;
					this.SendPropertyChanged("Pro_Type");
					this.OnPro_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveExpireDate", DbType="NVarChar(50)")]
		public string HaveExpireDate
		{
			get
			{
				return this._HaveExpireDate;
			}
			set
			{
				if ((this._HaveExpireDate != value))
				{
					this.OnHaveExpireDateChanging(value);
					this.SendPropertyChanging();
					this._HaveExpireDate = value;
					this.SendPropertyChanged("HaveExpireDate");
					this.OnHaveExpireDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoponValue", DbType="Real")]
		public System.Nullable<float> CoponValue
		{
			get
			{
				return this._CoponValue;
			}
			set
			{
				if ((this._CoponValue != value))
				{
					this.OnCoponValueChanging(value);
					this.SendPropertyChanging();
					this._CoponValue = value;
					this.SendPropertyChanged("CoponValue");
					this.OnCoponValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Name", DbType="NVarChar(150)")]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this.OnCompany_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Name = value;
					this.SendPropertyChanged("Company_Name");
					this.OnCompany_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effective_Name", DbType="NVarChar(150)")]
		public string Effective_Name
		{
			get
			{
				return this._Effective_Name;
			}
			set
			{
				if ((this._Effective_Name != value))
				{
					this.OnEffective_NameChanging(value);
					this.SendPropertyChanging();
					this._Effective_Name = value;
					this.SendPropertyChanged("Effective_Name");
					this.OnEffective_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackColor", DbType="NVarChar(50)")]
		public string BackColor
		{
			get
			{
				return this._BackColor;
			}
			set
			{
				if ((this._BackColor != value))
				{
					this.OnBackColorChanging(value);
					this.SendPropertyChanging();
					this._BackColor = value;
					this.SendPropertyChanged("BackColor");
					this.OnBackColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewPath", DbType="NVarChar(250)")]
		public string NewPath
		{
			get
			{
				return this._NewPath;
			}
			set
			{
				if ((this._NewPath != value))
				{
					this.OnNewPathChanging(value);
					this.SendPropertyChanging();
					this._NewPath = value;
					this.SendPropertyChanged("NewPath");
					this.OnNewPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Printer_Name", DbType="NVarChar(50)")]
		public string Printer_Name
		{
			get
			{
				return this._Printer_Name;
			}
			set
			{
				if ((this._Printer_Name != value))
				{
					this.OnPrinter_NameChanging(value);
					this.SendPropertyChanging();
					this._Printer_Name = value;
					this.SendPropertyChanged("Printer_Name");
					this.OnPrinter_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDayGym", DbType="Int")]
		public System.Nullable<int> NumDayGym
		{
			get
			{
				return this._NumDayGym;
			}
			set
			{
				if ((this._NumDayGym != value))
				{
					this.OnNumDayGymChanging(value);
					this.SendPropertyChanging();
					this._NumDayGym = value;
					this.SendPropertyChanged("NumDayGym");
					this.OnNumDayGymChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveRicaby", DbType="NVarChar(50)")]
		public string HaveRicaby
		{
			get
			{
				return this._HaveRicaby;
			}
			set
			{
				if ((this._HaveRicaby != value))
				{
					this.OnHaveRicabyChanging(value);
					this.SendPropertyChanging();
					this._HaveRicaby = value;
					this.SendPropertyChanged("HaveRicaby");
					this.OnHaveRicabyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveStore", DbType="NVarChar(50)")]
		public string HaveStore
		{
			get
			{
				return this._HaveStore;
			}
			set
			{
				if ((this._HaveStore != value))
				{
					this.OnHaveStoreChanging(value);
					this.SendPropertyChanging();
					this._HaveStore = value;
					this.SendPropertyChanged("HaveStore");
					this.OnHaveStoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintINBasicBranch", DbType="NVarChar(50)")]
		public string PrintINBasicBranch
		{
			get
			{
				return this._PrintINBasicBranch;
			}
			set
			{
				if ((this._PrintINBasicBranch != value))
				{
					this.OnPrintINBasicBranchChanging(value);
					this.SendPropertyChanging();
					this._PrintINBasicBranch = value;
					this.SendPropertyChanged("PrintINBasicBranch");
					this.OnPrintINBasicBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveSize", DbType="NVarChar(50)")]
		public string HaveSize
		{
			get
			{
				return this._HaveSize;
			}
			set
			{
				if ((this._HaveSize != value))
				{
					this.OnHaveSizeChanging(value);
					this.SendPropertyChanging();
					this._HaveSize = value;
					this.SendPropertyChanged("HaveSize");
					this.OnHaveSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Price", DbType="Real")]
		public System.Nullable<float> Buy_Price
		{
			get
			{
				return this._Buy_Price;
			}
			set
			{
				if ((this._Buy_Price != value))
				{
					this.OnBuy_PriceChanging(value);
					this.SendPropertyChanging();
					this._Buy_Price = value;
					this.SendPropertyChanged("Buy_Price");
					this.OnBuy_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadPro_ID", DbType="Int")]
		public System.Nullable<int> HeadPro_ID
		{
			get
			{
				return this._HeadPro_ID;
			}
			set
			{
				if ((this._HeadPro_ID != value))
				{
					this.OnHeadPro_IDChanging(value);
					this.SendPropertyChanging();
					this._HeadPro_ID = value;
					this.SendPropertyChanged("HeadPro_ID");
					this.OnHeadPro_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(50)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class AllCustomersResult
	{
		
		private int _مسلسل;
		
		private string _اسم_العميل;
		
		private string _عنوان_العميل;
		
		private string _رقم_التليفون;
		
		public AllCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_مسلسل", DbType="Int NOT NULL")]
		public int مسلسل
		{
			get
			{
				return this._مسلسل;
			}
			set
			{
				if ((this._مسلسل != value))
				{
					this._مسلسل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[اسم العميل]", Storage="_اسم_العميل", DbType="NVarChar(250)")]
		public string اسم_العميل
		{
			get
			{
				return this._اسم_العميل;
			}
			set
			{
				if ((this._اسم_العميل != value))
				{
					this._اسم_العميل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[عنوان العميل]", Storage="_عنوان_العميل", DbType="NVarChar(250)")]
		public string عنوان_العميل
		{
			get
			{
				return this._عنوان_العميل;
			}
			set
			{
				if ((this._عنوان_العميل != value))
				{
					this._عنوان_العميل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[رقم التليفون]", Storage="_رقم_التليفون", DbType="NVarChar(50)")]
		public string رقم_التليفون
		{
			get
			{
				return this._رقم_التليفون;
			}
			set
			{
				if ((this._رقم_التليفون != value))
				{
					this._رقم_التليفون = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
